from decimal import Decimal

# 100 quality checklist items across 6 service areas
# max_points = 1.0 per item (aggregate = percentage of 100 total points)
CHECKLIST_ITEMS = [
    # ── HYGIENE (15 items) ──────────────────────────────────────────────────
    {"code": "HYG-01", "description": "Station de lavage des mains fonctionnelle avec eau et savon", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-02", "description": "Poubelles à couvercle disponibles dans chaque salle", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-03", "description": "Gestion sécurisée des déchets piquants (boîtes de sécurité)", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-04", "description": "Salle d'accouchement propre et équipée (drap propre, éclairage)", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-05", "description": "Autoclave ou stérilisateur à vapeur fonctionnel et registre d'utilisation à jour", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-06", "description": "Latrine réservée au personnel, propre et fonctionnelle", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-07", "description": "Latrine réservée aux patients (hommes/femmes séparées si possible)", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-08", "description": "Protocole de décontamination du matériel affiché et respecté", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-09", "description": "Eau potable disponible en permanence (réserve ou réseau)", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-10", "description": "Literie propre changée entre chaque patient hospitalisé", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": "Hôpital District"},
    {"code": "HYG-11", "description": "Plan de nettoyage quotidien des salles affiché et signé", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-12", "description": "Incinérateur ou fosse à déchets biomédicaux fonctionnel", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-13", "description": "Port de gants systématique lors des soins invasifs", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-14", "description": "Désinfectant (alcool 70° ou chlorhexidine) disponible aux postes de soins", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "HYG-15", "description": "Registre de contrôle de la stérilisation tenu à jour (date, lot)", "service_area": "Hygiene", "max_points": Decimal("1"), "applies_to_facility_type": None},

    # ── PATIENT RECORDS (20 items) ───────────────────────────────────────────
    {"code": "REC-01", "description": "Registre des consultations curatives à jour (date, diagnostic, traitement)", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-02", "description": "Registre des accouchements à jour (partogramme renseigné)", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-03", "description": "Registre CPN tenu par visite (CPN1 à CPN4)", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-04", "description": "Registre vaccination enfant à jour (par antigène, par date)", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-05", "description": "Registre planification familiale à jour (méthode, date d'adoption)", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-06", "description": "Carnet de santé mère remis à chaque femme enceinte inscrite en CPN", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-07", "description": "Carnet de santé enfant remis à la naissance", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-08", "description": "Actes de naissance enregistrés ou transfert vers état civil dans les 30 jours", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-09", "description": "Dossiers patients hospitalisés archivés avec antécédents et évolution", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": "Hôpital District"},
    {"code": "REC-10", "description": "Registre TB (DOTS) à jour avec résultats d'expectoration", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-11", "description": "Registre VIH/PTME à jour avec statut sérologique et traitement", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-12", "description": "Rapport mensuel DHIS2 soumis dans les délais (avant le 5 du mois suivant)", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-13", "description": "Formulaires de déclaration trimestrielle FBP remplis sans ratures ni lacunes", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-14", "description": "Registre des décès maternels et néonataux tenu (audit de décès)", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-15", "description": "Fiches de référence/contre-référence complétées et archivées", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-16", "description": "Registre nutrition (URENAM) à jour (admission, suivi, sortie)", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-17", "description": "Registre des soins dentaires tenu", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-18", "description": "Rapport d'activités mensuel validé par le responsable", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-19", "description": "Cartes de rendez-vous remises aux patients sous traitement chronique", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "REC-20", "description": "Registres accessibles et classés par année sans déchirures ni mouillures", "service_area": "Patient Records", "max_points": Decimal("1"), "applies_to_facility_type": None},

    # ── DRUG MANAGEMENT (20 items) ───────────────────────────────────────────
    {"code": "MED-01", "description": "Stock de médicaments essentiels (liste OMS) disponible sans rupture", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-02", "description": "Chaîne du froid fonctionnelle (température 2-8°C, relevés journaliers)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-03", "description": "Aucun médicament périmé stocké en pharmacie", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-04", "description": "Registre de pharmacie tenu (entrées/sorties par DCI)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-05", "description": "Vaccins disponibles pour les 6 antigènes du PEV de base", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-06", "description": "Solutés de perfusion disponibles (NaCl 0.9%, SG 5%, Ringer)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-07", "description": "Oxytocine disponible et stockée au froid (prévention HPP)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-08", "description": "TDR paludisme disponibles en stock suffisant", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-09", "description": "ARV disponibles pour les patients sous traitement sans rupture", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-10", "description": "Médicaments TB (DOTS) en stock (rifampicine, isoniazide, pyrazinamide)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-11", "description": "Suppléments nutritionnels (ATPE) disponibles en stock (URENAM)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-12", "description": "Sulfate de magnésium disponible (traitement éclampsie)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-13", "description": "Acide folique et fer disponibles pour les femmes enceintes", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-14", "description": "Médicaments stockés selon règle FIFO (premier entré, premier sorti)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-15", "description": "Inventaire physique mensuel de la pharmacie réalisé et signé", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-16", "description": "Contraceptifs (implant, DIU, pilule, préservatifs) disponibles sans rupture", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-17", "description": "Antibiotiques essentiels (amoxicilline, cotrimoxazole) disponibles", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-18", "description": "Kit de soins néonataux disponible (cordon, aspiration, chaleur)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-19", "description": "Antalgiques (paracétamol, ibuprofène) disponibles", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MED-20", "description": "Sérum antivenimeux disponible (zones à risque scorpions/serpents)", "service_area": "Drug Management", "max_points": Decimal("1"), "applies_to_facility_type": None},

    # ── EQUIPMENT (15 items) ─────────────────────────────────────────────────
    {"code": "EQP-01", "description": "Table d'accouchement fonctionnelle et propre", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-02", "description": "Tensiomètre et stéthoscope fonctionnels disponibles", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-03", "description": "Balance pèse-bébé fonctionnelle et étalonnée", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-04", "description": "Aspirateur de mucosités néonatales fonctionnel", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-05", "description": "Source d'éclairage de secours (lampe/groupe électrogène) fonctionnelle", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-06", "description": "Glucomètre et bandelettes disponibles et fonctionnels", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-07", "description": "Thermomètre médical disponible", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-08", "description": "Oxymètre de pouls fonctionnel", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-09", "description": "Matériel de perfusion (cathéters, tubulures, potences) disponible", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-10", "description": "Microscope fonctionnel pour examen des expectorations (TB)", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-11", "description": "Kit d'accouchement d'urgence disponible et complet", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-12", "description": "Couveuse ou lit chauffant pour nouveau-né (maternité district+)", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": "Hôpital District"},
    {"code": "EQP-13", "description": "Réfrigérateur à vaccins fonctionnel avec alarme de température", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-14", "description": "Pesée mère disponible (balance adulte)", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "EQP-15", "description": "Véhicule d'évacuation ou accord formel de référence disponible", "service_area": "Equipment", "max_points": Decimal("1"), "applies_to_facility_type": None},

    # ── CLINICAL PROTOCOLS (20 items) ────────────────────────────────────────
    {"code": "PROT-01", "description": "Protocole PCIME affiché et utilisé pour les consultations enfant < 5 ans", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-02", "description": "Protocole CPN standard (10 contacts OMS) connu du personnel", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-03", "description": "Partogramme utilisé pour chaque accouchement", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-04", "description": "Protocole GATPA appliqué (délivrance dirigée, oxytocine systématique)", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-05", "description": "Protocole DOTS affiché et suivi pour chaque patient TB", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-06", "description": "Test de grossesse ou dépistage VIH proposé à chaque CPN1", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-07", "description": "Protocole PTME appliqué pour les femmes VIH+ enceintes", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-08", "description": "Groupage sanguin réalisé à chaque CPN (ou résultat disponible)", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-09", "description": "Protocole de réanimation néonatale disponible et formation récente", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-10", "description": "Antibioprophylaxie systématique lors des césariennes", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": "Hôpital District"},
    {"code": "PROT-11", "description": "Conseil et dépistage VIH disponible (CDV) — registre tenu", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-12", "description": "Protocole gestion PAL (paludisme grave) affiché", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-13", "description": "Prescription médicale conforme (DCI, dosage, durée) sur 95% des ordonnances vérifiées", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-14", "description": "Mesure du périmètre brachial (PB) systématique enfant 6-59 mois", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-15", "description": "Référence systématique des complications obstétricales identifiées", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-16", "description": "Antipaludéen préventif intermittent (TPI) administré à chaque CPN2+", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-17", "description": "Vitamine A administrée aux enfants de 6-59 mois (semestrielle)", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-18", "description": "Déparasitage (albendazole) administré aux enfants 12-59 mois", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-19", "description": "Plan de sécurité transfusionnelle disponible (liste donneurs, accord hôpital référence)", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "PROT-20", "description": "Personnel en mesure de réaliser une consultation CPN conforme (observation directe)", "service_area": "Clinical Protocols", "max_points": Decimal("1"), "applies_to_facility_type": None},

    # ── MANAGEMENT (10 items) ────────────────────────────────────────────────
    {"code": "MGT-01", "description": "Réunion du personnel mensuelle avec procès-verbal signé", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MGT-02", "description": "Rapport de supervision trimestrielle disponible et commenté", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MGT-03", "description": "Plan d'action annuel de la structure disponible et en cours d'exécution", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MGT-04", "description": "Registre des plaintes patients tenu (comité de gestion)", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MGT-05", "description": "Compte rendu financier trimestriel validé par le comité de gestion", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MGT-06", "description": "Affichage des tarifs des soins (gratuité ciblée affichée)", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MGT-07", "description": "Organigramme et liste du personnel affichés à l'entrée", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MGT-08", "description": "Contrat de performance FBP signé entre la structure et l'ACV", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MGT-09", "description": "Personnel clé présent lors de la visite de vérification (chef de structure)", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
    {"code": "MGT-10", "description": "Formation continue du personnel documentée (au moins 1 session dans le trimestre)", "service_area": "Management", "max_points": Decimal("1"), "applies_to_facility_type": None},
]
